### ISSUE TITLE
Detect SQLite keywords in column names

### ISSUE THREAD

**Issue by irgeek** [coderhs/csvsqlweb#1]
When the CSV file has column names that are [keywords in SQLite](https://www.sqlite.org/lang_keywords.html) the CSV silently fails to load.

In my case, the CSV had a column named `index`. When I changed it to `idx` the file loaded correctly. Perhaps you could add a tail to column names that are keywords so, for instance, a column name of `index` would be imported as `index_`. That would avoid the collision and stop the error that blocks loading the data. If you need test data, I was using the `organizations-10000.csv` file from [here](https://www.datablist.com/learn/csv/download-sample-csv-files).

**Comment by coderhs** [comment]
Thanks for reporting this. Really made my day, happy to see people checking out my code.

I agree with your suggestion, better to avoid using the keywords as it could either prevent from creating table or cause problem at some other time. Like when i tested the keyword abort and cascade, it did create table. But I think it might create issues when we run some queries against those columns.

I can give it a shot when I get a chance or would you be interested in writing a PR for this?
